### ISSUE TITLE
HTML Table VS ul/li to display database data

### ISSUE THREAD

**Issue by patdel0** [fac25/week3-authentication-Abby-Sumithra-Patrick-Lisa#30]
Which one is prefered?

**Comment by Abbbyccc** [comment]
A couple notes on a question @Patrick and @Abby  asked about presenting information in tables vs unordered lists. It mostly comes down to what your information is and how you want to present it. Is this information that would benefit from being presented in tabular form? Users will interact differently with a table as compared to a list or a series of cards. Tables make it easy to scan down a column and to compare and group entries with a particular property - is this useful for the information you’re presenting? A list makes browsing easier and (probably) more attractive. A nested list implies a hierarchy. Cards imply items that can stand alone: they could still be sorted and compared but they needn’t be. 

There are ways of making lists and tables accessible and responsive, but tables are fiddlier and a bit more restrictive. The MDN pages on the Table element (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table), as well as basic (https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Basics) and advanced features of HTML tables (https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced) go into this in some detail.
