### ISSUE TITLE
Compliments ✨ 

### ISSUE THREAD

**Issue by joe-dev-public** [fac25/week3-authentication-Abby-Sumithra-Patrick-Lisa#41]
- Neat, well-organised code and codebase.
- Nice use of modular markup components in `templates.js`.
- `getSharedBooks` + related query are a nice way of getting content on the home page 📚 
- [Optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) can be very handy ❔ ✅  
- The deployed site was working very well! (Until the last push :)
- Good README, nice to have local setup instructions 👍🏻

**Comment by Abbbyccc** [comment]
Thank you @joe-dev-public from the group!!
